[tool.poetry]
name = "ultrack"
version = "0.1.0"
description = ""
authors = ["Jordao Bragantini <jordao.bragantini@czbiohub.org>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
rich = "^12.5.1"
magicgui = "^0.5.1"
toml = "^0.10.2"
pydantic = "^1.9.1"
higra = "^0.6.5"
zarr = "^2.12.0"
napari = "^0.4.15"
pillow = "<9.2.0"  # tox wans't working for 9.2.0
numba = "^0.56.0"
blosc = "^1.10.6"
tensorstore = "0.1.16"
SQLAlchemy = "^1.4.40"
gurobipy = "^9.5.2"
seaborn = "^0.11.2"
imagecodecs = "^2022.8.8"
scikit-image = "^0.19.3"
cvxpy = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.20.0"
pytest-qt = "^4.1.0"
PyQt5 = "^5.15.7"
asv = "^0.5.1"

[tool.poetry.scripts]
ultrack = "ultrack.cli.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
